apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-app
          image: codewithajdotguru/products-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: "http"
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: products-app-secrets
                  key: mongo-db-url
