apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: codewithajdotguru/gateway
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: "http"
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 10
