apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    job: gateway-job
    app: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: gateway-port
      port: 3000
      targetPort: 3000
      nodePort: 31704
